rails-projet/prueba_final_Ajax/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :companies do
    resources :complains, only: :create
  end
  devise_for :users
  root 'companies#index'
end

rails-projet/prueba_final_Ajax/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

rails-projet/prueba_final_Ajax/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-projet/prueba_final_Ajax/app/models/company.rb
class Company < ApplicationRecord
  has_many :complains, dependent: :destroy
end

rails-projet/prueba_final_Ajax/app/models/complain.rb
class Complain < ApplicationRecord
  belongs_to :company
  belongs_to :user
end

rails-projet/prueba_final_Ajax/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :complains, dependent: :destroy
end

rails-projet/prueba_final_Ajax/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails-projet/prueba_final_Ajax/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :check_permission, only: %i[create show update destroy]

  def index
    @companies = Company.order('created_at DESC')
    @company = Company.new
  end

  def create
    @company = Company.new(
      name: params[:company][:name],
      # user_id: current_user.id
    )
    @company.save
    respond_to :js
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    respond_to :js
  end

  def edit
    @company = Company.find(params[:id])
    respond_to :js
  end

  def update
    @company = Company.find(params[:id])
    @company.name = params[:company][:name]
    @company.save
    respond_to :js
  end

  def show
    @company = Company.find(params[:id])
    respond_to :js
  end


  def check_permission
    redirect_to root_path, alert: 'No posee los permisos necesarios.' and return unless current_user
  end
end

rails-projet/prueba_final_Ajax/app/controllers/complains_controller.rb
class ComplainsController < ApplicationController
  def create
    @complain = Complain.new(
      content: params[:complain][:content],
      company: Company.find(params[:company_id]),
      user: current_user
    )
    @complain.save
    respond_to :js
  end
end

rails-projet/prueba_final_Ajax/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-projet/prueba_final_Ajax/app/helpers/companies_helper.rb
module CompaniesHelper
end

rails-projet/prueba_final_Ajax/app/helpers/complains_helper.rb
module ComplainsHelper
end

rails-projet/prueba_final_Ajax/app/views/companies/_company.html.erb
<li id="<%=company.id%>"><%= company.name %>
<%= link_to 'Detalle', company_path(company.id), data: {remote: true} %>
<%= link_to 'Editar', edit_company_path(company.id), data: {remote: true} %>
<%= link_to 'Eliminar', company, method: :delete, data: {confirm: '¿Estás seguro de eliminar la empresa?', remote: true} %></li>

rails-projet/prueba_final_Ajax/app/views/companies/_complain_form.html.erb
<%= form_with(model: [company, complain]) do |f| %>
<%= f.label :content %>
<%= f.text_field :content %>
<%= f.submit %>
<% end %>

<ul id= "company_complains_list">
<% company.complains.each do |c| %>
<li><%= c.content %></li>
<% end %>
</ul>

rails-projet/prueba_final_Ajax/app/views/companies/_form.html.erb
<%= form_with(model: @company) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

rails-projet/prueba_final_Ajax/app/views/companies/create.js.erb
$('#company_list').append('<%= j render @company %>')

rails-projet/prueba_final_Ajax/app/views/companies/destroy.js.erb
$("#<%=@company.id %>").toggle(1000);

rails-projet/prueba_final_Ajax/app/views/companies/edit.js.erb
$('.modal-body').html("<%= j render 'form', post: @company %>")
$('#modal-edit').modal('show')

rails-projet/prueba_final_Ajax/app/views/companies/index.html.erb
<h1>Listado de Empresas</h1>

<%= render 'form', company: @company %>

<ul id="company_list">
  <%= render @companies %>
</ul>

<%# Este es el modal: %>
<div id="modal-edit" class="modal fade" tabindex="-1" role="dialog">
 <div class="modal-dialog" role="document">
   <div class="modal-content">
     <div class="modal-header">
       <h2 class="modal-title">Reclamos</h2>
       <button type="button" class="close" data-dismiss="modal" aria-label="Close">
         <span aria-hidden="true">&times;</span>
       </button>
     </div>
     <div class="modal-body">

     </div>
   </div>
 </div>
</div>

rails-projet/prueba_final_Ajax/app/views/companies/index.js.erb
$('#company_list').html("<%= j render @companies %>");

rails-projet/prueba_final_Ajax/app/views/companies/show.js.erb
$('.modal-body').html("<h3><%= @company.name %></h3> <%= j render 'complain_form', company: @company, complain: Complain.new %>")
$('#modal-edit').modal('show')

rails-projet/prueba_final_Ajax/app/views/companies/update.js.erb
$('#<%= @company.id %>').replaceWith("<%= j render @company %>")
$('modal-edit').modal('hide')

rails-projet/prueba_final_Ajax/app/views/complains/create.js.erb
$('#company_complains_list').append("<li><%= @complain.content %></li>")

rails-projet/prueba_final_Ajax/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">Empresas</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">

  <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= admin_admin_users_path %>">Administrador</a>
      </li>
  </ul>
    <ul class="navbar-nav ml-auto">
     <% if user_signed_in? %>
      <li><a href="#" class="nav-link"><%=current_user.email %></a></li>
      <li><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
    <% else %>
      <li><%= link_to 'Inicia sesión', new_user_session_path, class: 'nav-link' %></li>
      <li><%= link_to 'Regístrate', new_user_registration_path, class: 'nav-link' %></li>
    <% end %>
    </ul>
  </div>
</nav>

rails-projet/prueba_final_Ajax/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script
			  src="https://code.jquery.com/jquery-3.3.1.min.js"
			  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
			  crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
    <%= yield %>

    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>